### ISSUE TITLE
we must enable place order and start production

### ISSUE THREAD

**Issue by HuangLiAlex** [Icanhascookie/DBProject#12]

**Comment by HuangLiAlex** [comment]
I have added placeorder1.php -- choose customer, placeorder2.php -- choose cookie, placeorder3.php -- enter amount and date. However, I don't know how to get the input data with PHP, the next should be just insert it into order() and orderquatity(), can someone help fix that? thanks a lot!

**Comment by magnusvmt** [comment]
ok, done. I used hidden fields instead of session variables.

**Comment by HuangLiAlex** [comment]
oh my, I just read the requirement again, we actually no need to place order, it becomes extra feature...
