### ISSUE TITLE
Database errors. Something strange is going on.

### ISSUE THREAD

**Issue by magnusvmt** [Icanhascookie/DBProject#2]
It can no longer find all tables we created. I'll investigate it.

**Comment by magnusvmt** [comment]
It seems like someone else is using our database and actually deleted all our tables and added their own. I don't know why they would, they could just have used different name. I'll change the database we're using.

**Comment by Icanhascookie** [comment]
MY friend that i worked with might be using it now too. We can probably just change our Table names if  it becomes a problem

**Comment by magnusvmt** [comment]
ah ok. I just changed to my username instead. Anyway, it should be solved now!

**Comment by HuangLiAlex** [comment]
or we could just change an database account?

**Comment by Icanhascookie** [comment]
Yes, thats also a solution. DOes ny of you have an unused account?

**Comment by HuangLiAlex** [comment]
you can use mine, db37  wait a min, i change a password

**Comment by magnusvmt** [comment]
Guys, I changed to mine 5 minutes ago, issue is closed :)

**Comment by HuangLiAlex** [comment]
ok
